version: '2'
services:
    kursevi-app:
        image: kursevi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://kursevi-postgresql:5432/kursevi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kursevi-postgresql:
        extends:
            file: postgresql.yml
            service: kursevi-postgresql
